### ISSUE TITLE
add scaling tests

### ISSUE THREAD

**Issue by Ladicek** [quarkus-qe/quarkus-openshift-test-suite#12]
Similar to https://github.com/rhoar-qe/thorntail-openshift-test-suite/tree/master/scaling

Should also gather some high-level metrics (how long does it take to scale from M to N etc.), but note these are hard to compare.

**Comment by rsvoboda** [comment]
fixed via https://github.com/quarkus-qe/quarkus-openshift-test-suite/pull/38
