### ISSUE TITLE
Ephemeral namespaces not working for Serverless tests

### ISSUE THREAD

**Issue by Sgitario** [quarkus-qe/quarkus-openshift-test-suite#125]
The Serverless module: https://github.com/quarkus-qe/quarkus-openshift-test-suite/tree/master/deployment-strategies/quarkus-serverless is not working when we run the suite using ephemeral namespace:

```
mvn -B -V clean verify -fae -pl app-metadata/deployment,app-metadata/runtime,common,deployment-strategies/quarkus-serverless -Dts.authenticated-registry -Dinclude.serverless
```

The problem is that the image is pushed by Quarkus OpenShift extension into the OpenShift registry and the namespace is generated when running the tests (not at build time).

**Comment by Ladicek** [comment]
It's not just `deployment-strategies/quarkus-serverless`, it's also `deployment-strategies/quarkus`. We briefly talked about that with @rsvoboda and @mjurc and while there are some hacky options, we didn't come up with a proper solution. The Quarkus way is just too rigid.

**Comment by pjgg** [comment]
Well, I think the original idea of "one test, one namespace" is a good idea, in terms of scalability (parallel execution), and isolation.  

 On the other hand, looks like the flows (live cycle) that you must follow with serverless and traditional deployment is different so as a developer your must be able to set `serverless-strategy` or leave the default one. 

The main issue that we have with serverless is that the deployment phase takes place in the compile-time, and will be deployed in the active namespace where you are running your `mvn` commands. So, this approach force you to re-use the same namespace to all your test (so this doesn't fit with the first point). 

So the question is, How we could redeploy our serverless application per test?

**Comment by Ladicek** [comment]
> the deployment phase takes place in the compile-time, and will be deployed in the active namespace where you are running your `mvn` commands

Yea exactly. I will take another look at #143 soon, promise -- I was stuck with some other issues but sorted them out finally.
