### ISSUE TITLE
Support propagation of system properties to internal maven command

### ISSUE THREAD

**Issue by llowinge** [quarkus-qe/quarkus-openshift-test-suite#216]
Using `UsingQuarkusPluginDeploymentStrategy ` and running `mvn clean test -Dquarkus.openshift.expose=true`, the system property is not picked up. It could be probably solved by adding new line `withSystemProperties` after https://github.com/quarkus-qe/quarkus-openshift-test-suite/blob/master/common/src/main/java/io/quarkus/ts/openshift/common/deploy/UsingQuarkusPluginDeploymentStrategy.java#L69.

**Comment by Sgitario** [comment]
Adding this property in the `application.properties` is not an option for you? This is how we use it in `deployment-strategies/quarkus` as an example. 
Our idea is to keep the system properties that need to be passed from arguments to the Quarkus plugin as minimal as possible, the rest of properties should go to `application.properties`.

Let me know if this helps.

**Comment by llowinge** [comment]
Yes, `application.properties` is an option, but i wanted to minimalize number of modifications which needs to be done in some sample quarkus app to be tested on Openshift (eg. modifying `application.properties`). But i understand that you don't want to modify the plugin too much via system properties to avoid some unwanted behaviour. I'm basically struggling only with `quarkus.openshift.expose=true` which is probably mandatory (framework does checks on readiness before it starts tests) unless you want to create it somehow by yourself ? Couldn't be that option be defaulted to true ?

**Comment by Sgitario** [comment]
> Yes, `application.properties` is an option, but i wanted to minimalize number of modifications which needs to be done in some sample quarkus app to be tested on Openshift (eg. modifying `application.properties`). But i understand that you don't want to modify the plugin too much via system properties to avoid some unwanted behaviour. I'm basically struggling only with `quarkus.openshift.expose=true` which is probably mandatory (framework does checks on readiness before it starts tests) unless you want to create it somehow by yourself ? Couldn't be that option be defaulted to true ?

Sure, I will provide a pull request to propagate all the quarkus.* properties to the plugin strategy.

**Comment by llowinge** [comment]
@Sgitario Great, thank you !

**Comment by rsvoboda** [comment]
> Sure, I will provide a pull request to propagate all the quarkus.* properties to the plugin strategy.

I like definition in `application.properties` because it is explicit.

I'm concerned about unwanted side effects of the PR to propagate all the quarkus.* properties to the plugin strategy.

Another approach could be propagation of controlled set of properties (e.g. quarkus.openshift.expose) when they are present.

**Comment by Sgitario** [comment]
> > Sure, I will provide a pull request to propagate all the quarkus.* properties to the plugin strategy.
> 
> I like definition in `application.properties` because it is explicit.
> 
> I'm concerned about unwanted side effects of the PR to propagate all the quarkus.* properties to the plugin strategy.
> 
> Another approach could be propagation of controlled set of properties (e.g. quarkus.openshift.expose) when they are present.

Sure, I will propagate only quarkus.openshift.expose then.

**Comment by rsvoboda** [comment]
Starting with Quarkus 1.13 the property will be deprecated. `quarkus.openshift.route.expose=true` is gonna be the new blessed one.

So maybe in the end propagating `quarkus.*` might be the reasonable way, we just need to thinks about possible implications.

**Comment by llowinge** [comment]
Thanks a lot @Sgitario !
