### ISSUE TITLE
If oc new-project was not run, TS fails ConfigMap on HTTP 503

### ISSUE THREAD

**Issue by Karm** [quarkus-qe/quarkus-openshift-test-suite#5]
It is apparently required to have a project created prior to running the TS, i.e. ```oc login``` is not enough on its own, one has to do ```oc new-project ``` too.

I suggest we parametrize the project name and let the TS create and delete the project.

**Comment by Ladicek** [comment]
I should have a PR for using ephemeral namespaces ready in a few minutes.

**Comment by Ladicek** [comment]
What I'd be interested in is your opinion on this: if the test fails, should the namespace be retained for investigation by default? My current implementation does that, but it probably isn't very safe.

**Comment by Karm** [comment]
@Ladicek It should be configurable IMHO.  I would definitely want it On on the stable branch on the prod cluster and I might want it Off while playing with random stuff...

**Comment by Ladicek** [comment]
I'm making it configurable as we speak, just thinking of the default value. Both make sense. I'll probably play it safe and make "retain on failure" an additional option.

**Comment by Ladicek** [comment]
I got myself dragged into a refactoring that wasn't well thought out, which is why I didn't submit the PR yet. I shall submit it later today or tomorrow morning.
