### ISSUE TITLE
Latest Master branch pom.xml seems broken when testing 1.3.2.CR1

### ISSUE THREAD

**Issue by samding01** [quarkus-qe/quarkus-openshift-test-suite#51]
We try to test MAVEN_REPO_ZIP_VERSION=1.3.2.CR1 with the latest master branch so that we can use the commitment of `commit b9745c87f4a0b2855efc13495756492689c28bc5`.
However it failed in build: see [jira comment](https://issues.redhat.com/browse/QUARKUS-205?focusedCommentId=14133366&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14133366) and [comment](https://issues.redhat.com/browse/QUARKUS-205?focusedCommentId=14133861&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14133861)

We was suggested to use the commit of `22d999b93c9c0ad0344e4c0682c0c9891072fd82` before. Since then there are some new commitments that prevents us cherry-pick the special commitment. We tried even manually updating the code, but get build errors. 

Thanks,

**Comment by rsvoboda** [comment]
Master is not guaranteed to be fully compatible with 1.3.z, there is https://github.com/quarkus-qe/quarkus-openshift-test-suite/tree/1.3 branch you should be using. This is passing on OCP 4.3 and OCP 3.11 on x86_64.

In the comments you linked there is wrong artifact pulled, this artifact is not productized.
https://repo.maven.apache.org/maven2/io/quarkus/quarkus-universe-bom/1.3.2.Final-redhat-00001/quarkus-universe-bom-1.3.2.Final-redhat-00001.pom

You should be using one of these BOMs:
 - https://maven.repository.redhat.com/ga/io/quarkus/quarkus-bom/1.3.2.Final-redhat-00001/quarkus-bom-1.3.2.Final-redhat-00001.pom
 - https://maven.repository.redhat.com/ga/com/redhat/quarkus/quarkus-universe-bom/1.3.2.Final-redhat-00001/quarkus-universe-bom-1.3.2.Final-redhat-00001.pom
