### ISSUE TITLE
LogFactory issue for external-applications

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-openshift-test-suite#70]
`mvn clean verify -Dquarkus-core-only -Dversion.quarkus=1.7.0.Final -Dquarkus.http.host=127.0.0.1 -pl app-metadata/deployment,app-metadata/runtime,common,external-applications/todo-demo-app`

gives
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 135.115 s <<< FAILURE! - in io.quarkus.ts.openshift.todo.demo.app.TodoDemoAppOpenShiftIT
[ERROR] io.quarkus.ts.openshift.todo.demo.app.TodoDemoAppOpenShiftIT Time elapsed: 135.114 s <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR] TodoDemoAppOpenShiftIT » NoClassDefFound org/apache/commons/logging/LogFactory
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by rsvoboda** [comment]
The issue is not in the application itself, checked with modified https://github.com/rsvoboda/todo-demo-app

org.apache.commons.logging.LogFactory is present in `commons-logging:commons-logging:1.2`
There are plenty of exlusions of `commons-logging:commons-logging` in https://github.com/quarkusio/quarkus/blob/master/bom/application/pom.xml

Might be the case that some dependency somehow requires commons-logging to be present.
There are some issues related to LogFactory in  https://github.com/quarkusio/quarkus/issues?q=is%3Aissue+is%3Aopen+LogFactory But nothing really close to our case.

**Comment by rsvoboda** [comment]
Played with various exclusions in `common` module, but what worked was to explicitly add `commons-logging:commons-logging:1.2` dependency.

**Comment by rsvoboda** [comment]
One more thing - I'm not really able to locate where the need for commons-logging comes from, I wasn't able to get stacktrace.

**Comment by Ladicek** [comment]
Funny, I took your fork of the example app, reverted the last commit, and still `mvn clean package` passes just fine.

**Comment by rsvoboda** [comment]
You need to run `verify`, IT test execution fails

**Comment by Ladicek** [comment]
Ah OK, with Java 11 based GraalVM and `mvn clean verify -Dnative`, indeed it fails. But with a completely different error, something about Hibernate failing to boot because of H2 :-)

**Comment by Ladicek** [comment]
Ah wait. I probably misunderstood that you got it failing just with the example app, outside of the OpenShift TS. Sorry, my bad.

**Comment by Ladicek** [comment]
OK, got it. This is because RestAssured depends on Apache HTTP Client, which depends on Apache Commons Logging.

If I comment out all usages of RestAssured, no CNFE occurs.

**Comment by rsvoboda** [comment]
@Ladicek thanks for investigation of the root cause! I didn't consider RestAssured as potential problem at all.

**Comment by Ladicek** [comment]
Yea, I think this might be considered a Quarkus usability issue. The dependency exclusions in the BOM are needed for Quarkus, but users are affected as well, if they actually use the BOM to manage things like RestAssured.

I'm looking at several versions of `io.quarkus:quarkus-bom` and it's been excluding Commong Logging from RestAssured for quite a while (it's there in 1.3.3). Not sure why we weren't hit sooner...

**Comment by rsvoboda** [comment]
https://github.com/quarkus-qe/quarkus-openshift-test-suite/tree/1.3 doesn't have external-applications module
